(deftemplate note
	(slot id)
	(slot measure_id)
	(slot score_id)
	(multislot pitch)
	(slot duration)
	(slot voice)
	(slot type)
	(slot stem)
)

(deftemplate measure
	(slot id)
	(slot score_id)
	(multislot notes_id)
)

(deffacts measures
	(measure (id 1) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 2) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 3) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 4) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 5) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 6) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 7) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 8) (score_id S1) (notes_id 1 2 3 4 ) )
	(measure (id 9) (score_id S1) (notes_id 1 ) )
	(measure (id 10) (score_id S1) (notes_id 1 ) )
	(measure (id 11) (score_id S1) (notes_id 1 2 3 ) )
	(measure (id 12) (score_id S1) (notes_id 1 2 3 ) )
	(measure (id 1) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 2) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 3) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 4) (score_id S2) (notes_id 1 2 3 4 5 ) )
	(measure (id 5) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 6) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 7) (score_id S2) (notes_id 1 2 3 4 5 6 ) )
	(measure (id 8) (score_id S2) (notes_id 1 2 3 ) )
	(measure (id 9) (score_id S2) (notes_id 1 2 3 ) )
	(measure (id 10) (score_id S2) (notes_id 1 ) )
)

(deffacts notes
	(note (id 1) (measure_id 1) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 1) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 1) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 1) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 2) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 2) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 2) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 2) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 3) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 3) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 3) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 3) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 4) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 4) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 4) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 4) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 5) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 5) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 5) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 5) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 6) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 6) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 6) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 6) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 7) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 7) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem up) )
	(note (id 3) (measure_id 7) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 7) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 8) (score_id S1) (pitch G 4) (duration 2) (voice 1) (type quarter) (stem down) )
	(note (id 2) (measure_id 8) (score_id S1) (pitch C 4) (duration 2) (voice 1) (type quarter) (stem down) )
	(note (id 3) (measure_id 8) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem down) )
	(note (id 4) (measure_id 8) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem down) )
	(note (id 1) (measure_id 9) (score_id S1) (pitch G 4) (duration 6) (voice 1) (type half) (stem up) )
	(note (id 1) (measure_id 10) (score_id S1) (pitch C 4) (duration 6) (voice 1) (type half) (stem up) )
	(note (id 1) (measure_id 11) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 2) (measure_id 11) (score_id S1) (pitch F 4) (duration 1) (voice 1) (type eighth) (stem up) )
	(note (id 3) (measure_id 11) (score_id S1) (pitch G 4) (duration 4) (voice 2) (type half) (stem up) )
	(note (id 1) (measure_id 12) (score_id S1) (pitch E 4) (duration 2) (voice 1) (type eighth) (stem down) )
	(note (id 2) (measure_id 12) (score_id S1) (pitch E 4) (duration 1) (voice 1) (type eighth) (stem down) )
	(note (id 3) (measure_id 12) (score_id S1) (pitch F 4) (duration 1) (voice 2) (type eighth) (stem down) )
	(note (id 1) (measure_id 1) (score_id S2) (pitch none none) (duration 8) (voice 1) (type half) (stem none) )
	(note (id 2) (measure_id 1) (score_id S2) (pitch none none) (duration 2) (voice 1) (type eighth) (stem none) )
	(note (id 3) (measure_id 1) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 1) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 5) (measure_id 1) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
  (note (id 6) (measure_id 1) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 2) (score_id S2) (pitch A 4) (duration 6) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 2) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 3) (measure_id 2) (score_id S2) (pitch G 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 2) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 5) (measure_id 2) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 6) (measure_id 2) (score_id S2) (pitch D 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 3) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 2) (measure_id 3) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 3) (measure_id 3) (score_id S2) (pitch F 4) (duration 4) (voice 1) (type quarter) (stem up) )
	(note (id 4) (measure_id 3) (score_id S2) (pitch none none) (duration 2) (voice 1) (type eighth) (stem none) )
	(note (id 5) (measure_id 3) (score_id S2) (pitch E 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 6) (measure_id 3) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 4) (score_id S2) (pitch A 4) (duration 6) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 4) (score_id S2) (pitch C 5) (duration 2) (voice 1) (type eighth) (stem down) )
	(note (id 3) (measure_id 4) (score_id S2) (pitch A 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 4) (score_id S2) (pitch G 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 5) (measure_id 4) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 5) (score_id S2) (pitch F 4) (duration 8) (voice 1) (type half) (stem up) )
	(note (id 2) (measure_id 5) (score_id S2) (pitch none none) (duration 2) (voice 1) (type eighth) (stem none) )
	(note (id 3) (measure_id 5) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 5) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 5) (measure_id 5) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
  (note (id 6) (measure_id 5) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 6) (score_id S2) (pitch A 4) (duration 6) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 6) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 3) (measure_id 6) (score_id S2) (pitch G 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 4) (measure_id 6) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 5) (measure_id 6) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 6) (measure_id 6) (score_id S2) (pitch D 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 7) (score_id S2) (pitch C 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 2) (measure_id 7) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 3) (measure_id 7) (score_id S2) (pitch F 4) (duration 4) (voice 1) (type quarter) (stem up) )
	(note (id 4) (measure_id 7) (score_id S2) (pitch none none) (duration 2) (voice 1) (type eighth) (stem none) )
	(note (id 5) (measure_id 7) (score_id S2) (pitch E 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 6) (measure_id 7) (score_id S2) (pitch F 4) (duration 2) (voice 1) (type eighth) (stem up) )
	(note (id 1) (measure_id 8) (score_id S2) (pitch C 4) (duration 6) (voice 1) (type quarter) (stem up) )
	(note (id 2) (measure_id 8) (score_id S2) (pitch E 3) (duration 2) (voice 1) (type eighth) (stem down) )
	(note (id 3) (measure_id 8) (score_id S2) (pitch D 5) (duration 2) (voice 2) (type eighth) (stem down) )
	(note (id 1) (measure_id 9) (score_id S2) (pitch G 4) (duration 8) (voice 2) (type half) (stem up) )
	(note (id 2) (measure_id 9) (score_id S2) (pitch none none) (duration 2) (voice 1) (type eighth) (stem none) )
	(note (id 3) (measure_id 9) (score_id S2) (pitch C 5) (duration 2) (voice 1) (type eighth) (stem down) )
	(note (id 1) (measure_id 10) (score_id S2) (pitch F 5) (duration 6) (voice 1) (type quarter) (stem down) )
)
